services:
  vcards:
    image: ghcr.io/metowolf/vcards:2025.12.25-082533
    restart: always
    ports:
      - "127.0.0.1:8008:5232"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://127.0.0.1:5232/.web/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
