services:
  beszel:
    image: henrygd/beszel:0.18
    restart: unless-stopped
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    environment:
      APP_URL: ${APP_URL}
    healthcheck:
      test: [ "CMD", "/beszel", "health", "--url", "http://127.0.0.1:8090" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  beszel-agent:
    image: henrygd/beszel-agent:0.18
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${KEY}
      TOKEN: ${TOKEN}
      HUB_URL: ${HUB}
    healthcheck:
      test: [ "CMD", "/agent", "health" ]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 20s
volumes:
  beszel_data:
  beszel_socket:
  beszel_agent_data:
